[package]
name = "zingo-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
rustyline = "11.0.0"
clap = "3.2.20"
log = "0.4.17"
shellwords = "1.1.0"
http = "0.2.4"
futures = "0.3.15"
rustls-pemfile = "1.0.0"
http-body = "0.4.4"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.23", features = ["http2"] }
prost = "0.10.0"
tokio =  { version = "1.24.2", features = ["full"] }
tokio-stream = "0.1.6"
tokio-rustls = "0.23.3"
tonic = {version = "0.7.0", features = ["tls", "tls-roots", "tls-webpki-roots"]}
tower = { version = "0.4" }
tower-http = { version = "0.2", features = ["add-extension"] }
webpki-roots = "0.21.0"
zingolib = { path = "../zingolib/" }
zingoconfig = { path = "../zingoconfig/" }
zingo-testutils = { path = "../zingo-testutils" }
portpicker = { workspace = true}
json = "0.12.4"

[dev-dependencies]
zcash_primitives = { workspace = true }
tempdir = { workspace = true }
portpicker = { workspace = true }
env_logger = "0.10.0"
zingolib = { path = "../zingolib/" }
bech32 = "0.9.0"
rand = "0.8.5"
hex = "0.3"
tracing-subscriber = "0.3.15"
itertools = "0.10.5"
bip0039 = "0.10.1"
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
futures-util = "0.3.28"
orchard = { workspace = true }
zcash_address = { workspace = true }
zcash_client_backend = { workspace = true }
shardtree = { workspace = true }

[features]
default = ["local_env"]
local_env = []
darkside_tests = []

[build-dependencies]
tonic-build = { workspace = true }
